name: libjpeg
description: 'Dart bindings for libjpeg.'
version: 0.0.1

environment:
  sdk: '>=3.3.0-71.0.dev <4.0.0'

dependencies:
  ffi: any
  libexif: any

dev_dependencies:
  ffigen: any
  flutter_lints: ^3.0.0

dependency_overrides:
  libexif:
    path: ../libexif

ffigen:
  output:
    bindings: 'lib/libjpeg.dart'
    symbol-file:
      output: 'package:libjpeg/symbols.yaml'
      import-path: 'package:libjpeg/libjpeg.dart' # If another package wants to import the symbols from package:libjpeg/symbols.yaml, they are in package:libjpeg/libjpeg.dart.
  name: 'LibJpeg'
  description: 'Dart bindings for libjpeg'
  exclude-all-by-default: true
  library-imports:
    libexif: 'package:libexif/libexif.dart' # Optional: Otherwise the lib import will be 'impl1' instead of `libexif`.
  import:
    symbol-files:
      - 'package:libexif/symbols.yaml'
  functions:
    include:
      - jpeg_.*
  structs:
    include:
      - _JPEG.*
    rename:
      '_Exif(.*)': 'Exif$1'
  enums:
    include:
      - JPEG.*
    exclude:
      - ExifFormat # Daco: why is this still getting defined in libjpeg.dart even though I told it to exclude?
      - ExifTag
  globals:
    include:
      - jpeg_.*
  typedefs:
    include:
      - JPEG.*
    exclude:
      - _?Exif.*
  compiler-opts:
    - '-I.'
    - '-I../libexif/' # Ensure that we find the headers from libexif.
  headers:
    entry-points:
      - 'libjpeg/**.h'
